"""empty message

Revision ID: 25f5644cb999
Revises: 4f37a633b528
Create Date: 2025-05-27 21:01:30.292254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f5644cb999'
down_revision = '4f37a633b528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('supervised_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('supervised_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('reason_for_consultation', sa.Text(), nullable=True),
    sa.Column('current_illness', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['supervised_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###
