"""empty message

Revision ID: 3eb9ba953842
Revises: 5941d3ef3bba
Create Date: 2025-05-22 14:36:41.597150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb9ba953842'
down_revision = '5941d3ef3bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('others', sa.Text(), nullable=False))

    with op.batch_alter_table('gynecological_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('others', sa.Text(), nullable=False))

    with op.batch_alter_table('medical_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervised_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('supervised_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['supervised_by'], ['id'])

    with op.batch_alter_table('non_pathological_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otherS', sa.Text(), nullable=False))
        batch_op.drop_column('other')

    with op.batch_alter_table('pathological_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traumatisms', sa.Text(), nullable=False))
        batch_op.drop_column('traumatisems')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathological_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traumatisems', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('traumatisms')

    with op.batch_alter_table('non_pathological_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('otherS')

    with op.batch_alter_table('medical_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('supervised_at')
        batch_op.drop_column('supervised_by')

    with op.batch_alter_table('gynecological_background', schema=None) as batch_op:
        batch_op.drop_column('others')

    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.drop_column('others')

    # ### end Alembic commands ###
