"""empty message

Revision ID: 4f37a633b528
Revises: 9e3805183118
Create Date: 2025-05-22 22:11:15.659022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f37a633b528'
down_revision = '9e3805183118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_surname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('second_surname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birth_day', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.Enum('femenino', 'masculino', 'otro', name='sextype'), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('sex')
        batch_op.drop_column('profession')
        batch_op.drop_column('birth_day')
        batch_op.drop_column('second_surname')
        batch_op.drop_column('first_surname')

    # ### end Alembic commands ###
