"""empty message

Revision ID: 5941d3ef3bba
Revises: 
Create Date: 2025-05-21 00:12:11.995294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5941d3ef3bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('role', sa.Enum('admin', 'profesional', 'paciente', 'estudiante', name='userrole'), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pre_aprobado', 'aprobado', 'inactivo', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medical_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('aprobado', 'rechazado', 'revision', name='filestatus'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('cancer', sa.Boolean(), nullable=False),
    sa.Column('heart_disease', sa.Boolean(), nullable=False),
    sa.Column('kidney_disease', sa.Boolean(), nullable=False),
    sa.Column('liver_disease', sa.Boolean(), nullable=False),
    sa.Column('mental_illness', sa.Boolean(), nullable=False),
    sa.Column('congenital_malformations', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gynecological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('menarche_age', sa.Integer(), nullable=False),
    sa.Column('pregnancies', sa.Integer(), nullable=False),
    sa.Column('births', sa.Integer(), nullable=False),
    sa.Column('c_sections', sa.Integer(), nullable=False),
    sa.Column('abortions', sa.Integer(), nullable=False),
    sa.Column('contraceptive_method', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('non_pathological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('economic_activity', sa.Text(), nullable=False),
    sa.Column('marital_status', sa.String(length=30), nullable=False),
    sa.Column('dependents', sa.Text(), nullable=False),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('recent_travels', sa.Text(), nullable=False),
    sa.Column('social_activities', sa.Text(), nullable=False),
    sa.Column('exercise', sa.Text(), nullable=False),
    sa.Column('diet_supplements', sa.Text(), nullable=False),
    sa.Column('hygiene', sa.Text(), nullable=False),
    sa.Column('tattoos', sa.Boolean(), nullable=False),
    sa.Column('piercings', sa.Boolean(), nullable=False),
    sa.Column('hobbies', sa.Text(), nullable=False),
    sa.Column('tobacco_use', sa.Text(), nullable=False),
    sa.Column('alcohol_use', sa.Text(), nullable=False),
    sa.Column('recreational_drugs', sa.Text(), nullable=False),
    sa.Column('addictions', sa.Text(), nullable=False),
    sa.Column('other', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pathological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('personal_diseases', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=False),
    sa.Column('hospitalizations', sa.Text(), nullable=False),
    sa.Column('surgeries', sa.Text(), nullable=False),
    sa.Column('traumatisems', sa.Text(), nullable=False),
    sa.Column('transfusions', sa.Text(), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=False),
    sa.Column('others', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('personal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('paternal_surname', sa.String(length=30), nullable=False),
    sa.Column('maternal_surname', sa.String(length=30), nullable=True),
    sa.Column('sex', sa.Enum('femenino', 'masculino', 'otro', name='sextype'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_data')
    op.drop_table('pathological_background')
    op.drop_table('non_pathological_background')
    op.drop_table('gynecological_background')
    op.drop_table('family_background')
    op.drop_table('medical_files')
    op.drop_table('users')
    # ### end Alembic commands ###
