"""empty message

Revision ID: 72a8e4c7f762
Revises: 
Create Date: 2025-06-04 21:26:54.996638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a8e4c7f762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('first_surname', sa.String(length=100), nullable=False),
    sa.Column('second_surname', sa.String(length=100), nullable=True),
    sa.Column('birth_day', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('administrador', 'profesional', 'paciente', 'estudiante', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('preaprobado', 'aprobado', 'inactivo', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('medical_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('supervised_by', sa.Integer(), nullable=True),
    sa.Column('supervised_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PROGRESS', 'REVIEW', 'APPROVED', 'CONFIRMED', name='filestatus'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('femenino', 'masculino', 'otro', name='sextype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('professional_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('academic_grade', sa.Enum('tecnico', 'profesionista', name='academicgrade'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('family_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('cancer', sa.Boolean(), nullable=False),
    sa.Column('heart_disease', sa.Boolean(), nullable=False),
    sa.Column('kidney_disease', sa.Boolean(), nullable=False),
    sa.Column('liver_disease', sa.Boolean(), nullable=False),
    sa.Column('mental_illness', sa.Boolean(), nullable=False),
    sa.Column('congenital_malformations', sa.Boolean(), nullable=False),
    sa.Column('others', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gynecological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('menarche_age', sa.Integer(), nullable=False),
    sa.Column('pregnancies', sa.Integer(), nullable=False),
    sa.Column('births', sa.Integer(), nullable=False),
    sa.Column('c_sections', sa.Integer(), nullable=False),
    sa.Column('abortions', sa.Integer(), nullable=False),
    sa.Column('contraceptive_method', sa.Text(), nullable=False),
    sa.Column('others', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('non_pathological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=False),
    sa.Column('economic_activity', sa.Text(), nullable=False),
    sa.Column('marital_status', sa.String(length=30), nullable=False),
    sa.Column('dependents', sa.Text(), nullable=False),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('recent_travels', sa.Text(), nullable=False),
    sa.Column('social_activities', sa.Text(), nullable=False),
    sa.Column('exercise', sa.Text(), nullable=False),
    sa.Column('diet_supplements', sa.Text(), nullable=False),
    sa.Column('hygiene', sa.Text(), nullable=False),
    sa.Column('tattoos', sa.Boolean(), nullable=False),
    sa.Column('piercings', sa.Boolean(), nullable=False),
    sa.Column('hobbies', sa.Text(), nullable=False),
    sa.Column('tobacco_use', sa.Text(), nullable=False),
    sa.Column('alcohol_use', sa.Text(), nullable=False),
    sa.Column('recreational_drugs', sa.Text(), nullable=False),
    sa.Column('addictions', sa.Text(), nullable=False),
    sa.Column('otherS', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pathological_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('personal_diseases', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=False),
    sa.Column('hospitalizations', sa.Text(), nullable=False),
    sa.Column('surgeries', sa.Text(), nullable=False),
    sa.Column('traumatisms', sa.Text(), nullable=False),
    sa.Column('transfusions', sa.Text(), nullable=False),
    sa.Column('allergies', sa.Text(), nullable=False),
    sa.Column('others', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patient_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_data')
    op.drop_table('pathological_background')
    op.drop_table('non_pathological_background')
    op.drop_table('gynecological_background')
    op.drop_table('family_background')
    op.drop_table('student_data')
    op.drop_table('professional_data')
    op.drop_table('personal_data')
    op.drop_table('medical_files')
    op.drop_table('users')
    # ### end Alembic commands ###
