"""empty message

Revision ID: a7041fb18a80
Revises: 72a8e4c7f762
Create Date: 2025-06-06 23:00:39.711062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7041fb18a80'
down_revision = '72a8e4c7f762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_pathological_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('others', sa.Text(), nullable=False))
        batch_op.drop_column('otherS')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_pathological_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otherS', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('others')

    # ### end Alembic commands ###
