"""empty message

Revision ID: d2b85934317b
Revises: 25f5644cb999
Create Date: 2025-05-28 19:17:15.918611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2b85934317b'
down_revision = '25f5644cb999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('medical_file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supervised_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confirmed_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('supervised_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reason_for_consultation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_illness', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name='interviews_confirmed_by_id_fkey'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='interviews_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_files.id'], name='interviews_medical_file_id_fkey'),
    sa.ForeignKeyConstraint(['supervised_by_id'], ['users.id'], name='interviews_supervised_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interviews_pkey')
    )
    # ### end Alembic commands ###
